service: serverlesCupidoOnlineApp

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: pereirafabio
  stage: dev
  region: sa-east-1
  environment:
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileBucketName}

plugins:
  - serverless-s3-sync

custom:
  appName: serverless-cupido-online-app
  fileBucketName: s3-file-bucket-${self:custom.appName}-${self:provider.stage}
  s3Sync:
    - bucketName: ${self:custom.fileBucketName}-demo
      localDir: uploadData

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileBucketName}-demo
